### ISSUE TITLE
大哥,前端源代码也放出来呗

### ISSUE THREAD

**Issue by usernameisnull** [sunshinev/go-space-chat#8]
web_resource下面的是已经编译好的吧?

**Comment by sunshinev** [comment]
web_resource/src 目录下是源码
js 主要是就是space.js

**Comment by sunshinev** [comment]
> web_resource下面的是已经编译好的吧?

编写完每次使用yarn build 重新打包就行

**Comment by usernameisnull** [comment]
> web_resource/src 目录下是源码
> js 主要是就是space.js

非常感谢,对前端不是太熟悉,没看清就发issue了,惭愧,惭愧
